image: golang:1.12.6

variables:
  REPO: gitlab.com
  GROUP: CasaTampieri
  PROJECT: dns

stages:
 - build

before_script:
  - mkdir -p $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds
  - cp -r $CI_PROJECT_DIR $GOPATH/src/$REPO/$GROUP/$PROJECT
  - ln -s $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds/$GROUP
  - go get -v -d ./...

build:
  stage: build
  script:
    - GOOS=linux GOARCH=arm GOARM=7 go build *.go
