image: golang:latest

variables:
  REPO: gitlab.com
  GROUP: CasaTampieri
  PROJECT: dns

stages:
 - build

build:
  stage: build
  script:
    - go get
    - GOOS=linux GOARCH=arm GOARM=7 go build *.go
